options:
  kubeflow-trainer-image:
    default: ghcr.io/kubeflow/trainer/trainer-controller-manager
    description: |
      Container image to be used by the Kubeflow Trainer workload.
    type: string
  jobset-image:
    default: us-central1-docker.pkg.dev/k8s-staging-images/jobset/jobset:v0.10.1
    description: |
      Container image to be used by the JobSet workload.
    type: string
  lws-image:
    default: us-central1-docker.pkg.dev/k8s-staging-images/lws/lws:main
    description: |
      Container image to be used by the Leader Worker Set workload.
    type: string