options:
  training-operator-image:
    default: docker.io/charmedkubeflow/training-operator:1.9.3-0704095
    description: |
      Container image to be used by the training-operator workload.
    type: string
