name: On Push

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
    - main-v2
    - track/2**

jobs:

  tests:
    name: Run Tests
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in series with tests, and only publishes if tests passes
  publish-charm:
    name: Publish Charm
    runs-on: ubuntu-24.04
    needs: tests

    steps:
      - name: Determine destination channel
        id: destination-channel
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          if [ $GIT_BRANCH = main-v2 ]; then
            destination_channel="latest/edge"
          else
            destination_channel=''
          fi
          echo "destination_channel=$destination_channel" >> "$GITHUB_OUTPUT"

      - name: Publish Charm
        uses: ./.github/workflows/publish.yaml
        with:
          destination_channel: ${{ steps.destination-channel.outputs.destination_channel }}
          secrets: inherit
